# This is Foreman's configuration file. You can edit it to tell Foreman about
# new tools that you'd like to install, or to change versions of tools you
# already have.

# When adding new tools, make sure to run `foreman install` so that their
# binaries are installed.

[tools]
rojo = { github = "rojo-rbx/rojo", version = "7.5.1" }
